api/README.md
=> Add Syntax Highlighting to Spec Readme

api/Conduit.postman_collection.json, api/README.md
Updated postman collection to include separate requests for optional auth endpoints.
Changed filename to reflect correct format.
Removed the property 'id' from user tests.
Added the missing body and tagList on the example response.
=> Updated postman collection and api spec readme

.gitignore, api/Conduit.postman_collection.json, api/Conduit.postman_integration_test_environment.json
=> Adding Support for Automated Postman Collection Testing with Newman

.travis.yml, README.md, package.json
@gothinkster/realworld-admins Any objections to merging this?
=> Updating npm test script to run newman integration tests

api/README.md
Few suggestions based on development of [Rust backend](https://github.com/hsharpsoftware/rust-realworld-example-app) and connecting it to the frontends.
=> CORS and Content-Type suggestion

.travis.yml, api/Conduit.postman_collection.json
Fixes #149 
Build passing: https://travis-ci.org/anishkny/realworld/builds/300826986#L421
=> Parameterize email/password in API Postman collection

README.md
Just to see what it could look like
Would close #150
=> Add Fullstack section and description

etc/backend-repos.yaml
=> Add BE Haskell / Yasod

README.template.md
=> docs(readme.template): typo fix

etc/backend-repos.yaml
Pure ruby with a particular architectural style.
We decided to write this to provide actual working examples with a series of articles we have written / plan to write.
Thanks for creating the RealWorld spec, btw. I think it's a very useful idea ;)
=> Add Ruby & Colmena backend example app

etc/frontend-repos.yaml
Closes #303 by adding a completed implementation of the Real World spec for PureScript, a strongly-typed, pure functional language that compiles to JavaScript. The language is in production at companies including SlamData, Lumi, CollegeVine, Awake Security, CitizenNet, and others, and I think it makes a fine addition to the real world project!
https://github.com/thomashoneyman/purescript-halogen-realworld
The repository already has 75 stars at the moment and has had reviews from members of the PureScript community. I think it's ready to be a part of the official Thinkster repository and I'd love to take care of whatever loose ends are necessary to get this merged.
Thanks!
=> Add PureScript + Halogen

etc/backend-repos.yaml
As discussed in [Issue 270](https://github.com/gothinkster/realworld/issues/270), I've added the functional ASP.NET Core implementation.
=> Added the 'Functional ASP.NET Core backend implementation.

etc/backend-repos.yaml
=> Add backend: Go Clean Architecture

etc/frontend-repos.yaml
=> Add frontend: Imba

README.template.md
@anishkny and @Cameron-C-Chapman have poured so much amazing work into this project over the past few years, and RealWorld would never have grown to this size (nor will it keep growing) without their continued efforts.
While Albert and I spent a lot of time initially getting RW off the ground, our contributions have been slim as of late. As such, I'd like to amend the readme to list Anish & Cameron as the primary/core maintainers of this project. They most certainly deserve it. (Also, it'll help me sleep better 😛)
Anish/Cameron- would you like to do the honors? :)
=> List Anish & Cameron as the Core Maintainers

etc/frontend-repos.yaml
@hcavalieri @anishkny I belive this can be added here? I saw there are couple of things to finish but nothing tha should prevent us to add this. Just for the sake of #342 😊
PS. Probably we shuold also update the logo and include Stencil icon?
=> Add frontend: Stencil.js

etc/backend-repos.yaml, etc/frontend-repos.yaml
Fixes #138, #193, #345, #401, #402.
=> feat: Add more repos

etc/backend-repos.yaml, etc/frontend-repos.yaml
=> Add new repos for Nov 2019

etc/backend-repos.yaml
=> Add backend: Pyramid

etc/frontend-repos.yaml
The original author was not updated, and I created a version using Preact X.
close #169
=> feat: add Preact X

etc/mobile-repos.yaml
Repo: https://github.com/flexsurfer/conduitrn
DEMO: https://www.youtube.com/watch?v=aq1QMq6_E14&list=PLRSmGfvI8FLo-EgYJw4PoFEbpnKNA0dh9
Development process: https://www.youtube.com/watch?v=5k2T126JFCY
DEMO APK: https://github.com/flexsurfer/conduitrn/blob/master/app-release.apk
=> add React Native (ClojureScript and re-frame)

etc/frontend-repos.yaml
close #559 
@anishkny All features were done, please review it. Thank you~
=> [Front-end] Add vue3 + vite repo

etc/frontend-repos.yaml
Riot.js projects were merged #606
@abdusabri 
Thanks. Please check it.
=> Update Riot repos

etc/backend-repos.yaml
Add FastAPI implementation.
Closes #520.
@abdusabri hi! Review this, please :)
=> add FastAPI implementation

etc/frontend-repos.yaml
Closes #518 
@Weedshaker I've created this PR to close your issue and add the repo/project to the README. 
Have a look and let me know if you have any comments or questions.
Once the PR is merged, the repo would appear in the README within 24 hours as it is auto-generated :)
=> Add event driven vanilla JS web components

README.md, README.template.md
=> fix: update Sandeesh profile link

api/Conduit.postman_collection.json
This is exactly the same as the previous test with login,
but this time without login.
This catches some JSON serialization errors that I had observed in a
backend implementation.
=> Test comment GET without login on run-api-tests.sh

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/feature-request.md, .github/PULL_REQUEST_TEMPLATE.md, contributing.md
update contributing.md
add github templates
related to #663
=> feat(project): add community guidelines

.github/CODEOWNERS
Issue Number: #686 
Added the CODEOWNERS file.
Hi @geromegrignon, how does this look?
Let me know if this needs any changes.
Thanks
=> feat: Add CODEOWNERS file to the .github folder

documentation/docusaurus.config.js
The Docusarus configuration includes the default URL link.
The Docusarus configuration includes the GitHub Pages URL link.
=> docs: update website url

.github/workflows/deploy-documentation.yml, .github/workflows/test-documentation.yml
The CI doesn't include a way to test the build of the documentation 
add test-documentation github action
rename documentation action to deploy-documentation
=> docs: add test-documentation github action

documentation/docs/specs/backend-specs/endpoints.md, documentation/docs/specs/frontend-specs/styles.md, documentation/package-lock.json
closes gothinkster/realworld#736
Resolves #736 
Some links in the documentation would not work.
Issue Number: #736 
The links work
=> docs: fix dead link

.github/workflows/bump.yml
The API documentation is hosted on the demo app (https://conduit.productionready.io/api-docs).
The API Documentation is hosted by bump.sh
=> feat: add bump github action

.github/workflows/deploy-documentation.yml, .github/workflows/test-documentation.yml
update node version used for GitHub Actions due to Docusaurus latest version requirement
GitHub Actions is using node version 12.
GitHub Actions is using node version 14.
=> chore: update GitHub Actions node version to 14

documentation/package-lock.json, documentation/package.json
Reverts gothinkster/realworld#913
=> Revert "chore(deps): bump @mdx-js/react from 1.6.22 to 2.1.1 in /documentation"

documentation/docusaurus.config.js, documentation/package-lock.json, documentation/package.json
The website uses Docusaurus beta-6 version.
The website uses Docusaurus beta-20 version.
=> chore: update docusaurus version to 20

api/openapi.yml
#close 950
The API Documentation include the token in User request body in place of the password.
Issue Number: #950 
The API Documentation include the password in User request body.
=> fix/950: change token to password reference

documentation/package-lock.json, documentation/package.json
The documentation is using docusaurus@2.0 beta version
The documentation is using docusaurus@2.1.0
=> feat: update docusaurus to 2.1.0

documentation/src/css/custom.css, documentation/src/pages/index.js
The realworld.io domain is down
Issue Number: #1004
A banner is added on the front page to warn users.
=> bug: realworld.io domain down

documentation/docs/specs/frontend-specs/templates.md
add logout button
the logout button is missing from the settings template.
Issue Number: #964
logout button added.
=> fix: settings template

.gitignore, api/openapi.yml
- added .vscode/ to gitinmore
- added operationId for "Get Tags"
- added tags globaly
=> feat: add tags & add lost operationId & refactoring components

api/openapi.yml
Issue Number: #1007
`User` response includes `password` field
`User` response includes `token` field
close #1007
=> fix/1007: rollback user response token field

package-lock.json, package.json
vulnerability on jsonwebtoken devDependancy.
fixed by updating express-jwt version
=> chore: fix jsonwebtoken vulnerability

apps/documentation/src/css/custom.css
=> refactor: home page height

apps/demo/public/index.css, apps/demo/src/app/stories/molecules/navbar.stories.tsx, apps/demo/src/app/stories/templates/settings.stories.tsx
=> refactor(design-system): add navbar molecule

.gitignore, package.json
=> refactor(design-system): add storybook commands

.github/workflows/chromatic.yml
=> feat(design-system): add chromatic GitHub action

apps/demo/public/index.css, apps/demo/src/app/stories/atoms/link/link.stories.mdx, apps/demo/src/app/stories/atoms/link/link.stories.tsx, apps/demo/src/app/stories/atoms/link/link.utils.tsx, apps/demo/src/app/stories/molecules/navbar.stories.tsx, apps/demo/src/app/stories/organisms/header.stories.tsx, apps/demo/src/app/stories/pages/article-form.stories.tsx, apps/demo/src/app/stories/pages/auth/create-account.stories.tsx, apps/demo/src/app/stories/pages/auth/login.stories.tsx, apps/demo/src/app/stories/pages/home.stories.tsx, apps/demo/src/app/stories/pages/profile.stories.tsx, apps/demo/src/app/stories/templates/article-form.stories.tsx, apps/demo/src/app/stories/templates/auth/create-account.stories.tsx, apps/demo/src/app/stories/templates/auth/login.stories.tsx, apps/demo/src/app/stories/templates/home.stories.tsx, apps/demo/src/app/stories/templates/profile.stories.tsx, apps/demo/src/app/stories/templates/settings.stories.tsx
=> feat(design-system): add link atoms

apps/demo/src/app/stories/atoms/button/button.stories.mdx, apps/demo/src/app/stories/atoms/link/link.stories.mdx
=> refactor(design-system): add states titles

apps/demo/public/index.css
add rounded border radius for buttons
=> refactor(design-system): add rounded border radius for buttons

apps/demo/public/index.css, apps/demo/src/app/stories/molecules/input-avatar.stories.tsx, apps/demo/src/app/stories/templates/settings.stories.tsx
=> feat(design-system): add input avatar example

apps/demo/public/index.css, apps/demo/src/app/stories/atoms/avatar.stories.tsx, apps/demo/src/app/stories/atoms/button/button.utils.tsx, apps/demo/src/app/stories/molecules/input-avatar.stories.tsx, apps/demo/src/app/stories/molecules/upload.stories.tsx, apps/demo/src/app/stories/organisms/header.stories.tsx, apps/demo/src/app/stories/pages/article-form.stories.tsx, apps/demo/src/app/stories/pages/auth/create-account.stories.tsx, apps/demo/src/app/stories/pages/auth/login.stories.tsx, apps/demo/src/app/stories/templates/article-form.stories.tsx, apps/demo/src/app/stories/templates/auth/create-account.stories.tsx, apps/demo/src/app/stories/templates/auth/login.stories.tsx, apps/demo/src/app/stories/templates/settings.stories.tsx
=> refactor(design-system): clear css classes

apps/demo/src/app/stories/organisms/article-form.stories.tsx, apps/demo/src/app/stories/organisms/article.stories.tsx, apps/demo/src/app/stories/organisms/auth/create-account.stories.tsx, apps/demo/src/app/stories/organisms/auth/login.stories.tsx, apps/demo/src/app/stories/organisms/home.stories.tsx, apps/demo/src/app/stories/organisms/profile.stories.tsx, apps/demo/src/app/stories/organisms/settings.stories.tsx, apps/demo/src/app/stories/pages/auth/login.stories.tsx
Move template stories to organisms
=> refactor(design-system): move templates to organisms

apps/demo/public/index.css, apps/demo/src/app/stories/molecules/input-field.stories.tsx, apps/demo/src/app/stories/organisms/auth/create-account.stories.tsx, apps/demo/src/app/stories/organisms/auth/login.stories.tsx, apps/demo/src/app/stories/pages/auth/create-account.stories.tsx, apps/demo/src/app/stories/pages/auth/login.stories.tsx
=> feat(design-system): update auth forms

apps/documentation/docs/intro.mdx
=> docs: update the number of implementations

.github/workflows/spammy-guardian.yml
some fake spam accounts created unsafe content on this repository.
The GitHub action moderates content using at least 10 tags mentions in the same issue/comment.
=> chore: add spammy-guardian

apps/demo/public/index.css, apps/demo/src/app/stories/styles/02-design-tokens.stories.mdx
=> feat(design-system): add color palette

apps/documentation/src/pages/index.js, apps/documentation/src/pages/index.module.css
add discussions wip implementations link
=> feat(documentation): add discussion link

apps/demo/public/index.css, apps/demo/src/app/stories/atoms/button/button.stories.tsx, apps/demo/src/app/stories/molecules/article-preview.stories.tsx, apps/demo/src/app/stories/molecules/input-field/input-field.mdx, apps/demo/src/app/stories/molecules/navbar/navbar.stories.tsx, apps/demo/src/app/stories/organisms/article-form.stories.tsx, apps/demo/src/app/stories/organisms/article-header.stories.tsx, apps/demo/src/app/stories/organisms/home-header.stories.tsx, apps/demo/src/app/stories/organisms/popular-tags.stories.tsx, apps/demo/src/app/stories/organisms/profile-header.stories.tsx, apps/demo/src/app/stories/pages/article-form.stories.tsx, apps/demo/src/app/stories/pages/article.stories.tsx, apps/demo/src/app/stories/pages/home.stories.tsx, apps/demo/src/app/stories/pages/profile.stories.tsx, apps/demo/src/app/stories/pages/settings.stories.tsx
=> feat(storybook): add page headers

apps/demo/public/index.css, apps/demo/src/app/stories/molecules/article-author.stories.tsx, apps/demo/src/app/stories/molecules/article-preview.stories.tsx, apps/demo/src/app/stories/organisms/article-form-header.stories.tsx, apps/demo/src/app/stories/organisms/article-form.stories.tsx, apps/demo/src/app/stories/organisms/article-header.stories.tsx, apps/demo/src/app/stories/organisms/auth/create-account.stories.tsx, apps/demo/src/app/stories/organisms/profile-header.stories.tsx, apps/demo/src/app/stories/pages/article-form.stories.tsx, apps/demo/src/app/stories/pages/article.stories.tsx, apps/demo/src/app/stories/pages/auth/create-account.stories.tsx, apps/demo/src/app/stories/pages/auth/login.stories.tsx, apps/demo/src/app/stories/pages/home.stories.tsx, apps/demo/src/app/stories/pages/profile.stories.tsx
=> feat(storybook): update page layouts

apps/demo/public/index.css, apps/demo/src/app/stories/pages/article-form.stories.tsx
=> feat(storybook): add preview tab

apps/demo/src/app/stories/atoms/icon/icon.mdx, apps/demo/src/app/stories/guidelines/04-accessibility.mdx, apps/demo/src/app/stories/guidelines/06-data-entry.mdx, apps/demo/src/app/stories/guidelines/07-data-validation.mdx, apps/demo/src/app/stories/styles/05-iconography.mdx
=> refactor(storybook): update to of reference

apps/demo/public/index.css, apps/demo/src/app/stories/molecules/banner/banner.stories.tsx, apps/demo/src/app/stories/organisms/settings.stories.tsx, apps/demo/src/app/stories/pages/settings.stories.tsx
=> feat(storybook): add profile link

apps/demo/public/index.css
=> fix(storybook): center home logo

apps/documentation/astro.config.mjs
fix typo for lefthand menu
fix typo for lefthand menu
fix typo for lefthand menu
=> docs: fix typo for menu
