gothinkster/realworld

api/Conduit.json.postman_collection
Was causing the API Call to fail.
=> Disabled Authorization Token for tags api

api/Conduit.postman_collection.json
I fixed an assertion description where it should say `... is false` instead of `... is true`.
=> Fix assertion description in Postman collection

README.md, etc/update-readme.js
It is not easy to compare which ranking changed exactly whenever the `README` is updated. This PR adds a rankings table in the comments of `README` one-per-line so that changes can be easily seen.
E.g. it will insert this for Frontends:
```markdown
```
=> feat: Add rankings one-per-line in comments to ease merges/updates

etc/update-readme.js
Displaying stars in the ranking comment causes unnecessary updates to README.
=> etc: Dont display stars in ranking comment

api/Conduit.postman_collection.json
I was doing some testing using the `run-api-tests` script and the `Create Comment for Article` assertion kept failing.
I am assuming that this meant to check the `createdAt` property of the comment instead of the article?
=> Fix assertion that should be on comment instead of article

README.md, README.template.md
Reorder - 2019 on top, followed by 2018 and 2017
=> Add Benchamarks for 2019

etc/backend-repos.yaml, etc/update-readme.js
If a repo is absent, `etc/update-readme.js` fails. E.g see [this build](https://travis-ci.org/github/gothinkster/realworld/builds/750714410).
This fixes it.
=> fix(update-readme): Do not fail if repo absent

spec/mobile_icons/ios/README.md
For reference: https://en.wikipedia.org/wiki/Wikipedia:Lists_of_common_misspellings/For_machines
=> Fix typo (change 'distirbution' to 'distribution')

etc/frontend-repos.yaml
The url is obsolete because master branch has been renamed to main some time ago
=> Fix Purescript + Halogen frontend logo url

etc/frontend-repos.yaml
After discussions in the Ember community we've decided to merge the "Ember Octane Realworld" app into the regular [Ember Realworld app](https://github.com/gothinkster/ember-realworld) so there is no longer a need for both anymore.
=> Remove Ember Octane

README.template.md, etc/fullstack-repos.yaml, etc/update-readme.js
- Created `etc/fullstack-repos.yaml` to add the [Layr/React](https://github.com/layrjs/react-layr-realworld-example-app) fullstack implementation.
- Modified `README.template.md` and `etc/update-readme.js` to auto-generate the fullstack section of `README.md` according to the content of `etc/fullstack-repos.yaml`.
=> Add Layr/React fullstack implementation

api/run-api-tests.sh
This allows running e.g. ./run-api-tests.sh --folder Register
to isolate just one specific test.
=> Forward arguments from run-api-tests.sh to newman

README.md
Jacek Shae's 2020 article appears to be missing from the links.
This PR adds it alongside his other articles.
=> Add missing 2020 comparison article

package.json
Previously we had newman": "^3.5.2", but if you install exactly 3.5.2
e.g. with npm install newman@3.5.2 the ./api/run-api-tests.sh fails with:
Unrecognized arguments: --global-var
because that feature was added after 3.5. It works with npm install
because if fetches the newer version currently 3.10 which has it.
Since I was upgrading this, I though I might as well update to 5 as it just
works.
=> feat(project): update to newman 5

api/openapi.yml
link issue : #256 
- Automatic conversion of existing `swagger.json` to `openapi.yml` by [Swagger Editor](https://editor.swagger.io/)
- I fixed the trivial part that was pointed out by the linter([OpenAPI Rules | Spectral](https://meta.stoplight.io/docs/spectral/docs/reference/openapi-rules.md#operation-tag-defined) )
- 200 -> "200"
- add operationId , Tags , etc
thank you
=> add openapi3.0.1 spec

api/openapi.yml
The default value for filtering is explicitly part of the description while already included as part of the API documentation itself
The `default is xx` mentions are remoed
=> refactor(openapi): remove default description for filtering

api/run-api-tests.sh, documentation/docs/specs/backend-specs/api-response-format.md, documentation/docs/specs/frontend-specs/api.md, documentation/docs/specs/mobile-specs/introduction.md
The demo API included in the documentation is `conduit.productionready.io`.
Issue Number: #790
The demo API included in the documentation is `api.realworld.io`.
=> feat: change demo api url to api.realworld.io

documentation/docs/specs/frontend-specs/api.md, documentation/docs/specs/mobile-specs/introduction.md
The current API documentation link is `https://api.realworld.io/api-docs`.
The new API documentation link for v2 is `https://bump.sh/doc/realworld`.
=> feat: change API documentation link to bump.sh

README.md
Fixed links to the realworld-docs.netlify.app in the readme
Removed /docs substring from the links in the main root
=> docs: fix links to the doc

README.md
fix link to the api spec at the top of the root readme
fix link to the api spec at the top of the root readme
=> docs fix api spec link at the top of the root readme
